### PR TITLE
Update to Godot 4.0 & refactoring with more static typing

### PR DESCRIPTION
**Pull request by OverloadedOrama**
Continuing the work from #20, this PR finalizes the porting process to Godot 4.0. Big thanks to @Gamemap for starting the process.

Issues from #20 solved (the 3.x version should not have these issues AFAIK):
- [x] Clicking on the DockableContainer in the Godot editor no longer reverts the layout. For some reason, the layout needed to be cloned when it was set in layout_editor_property.gd's `_ready()` method. Took me a whole day to debug and solve. 😅
- [x] Deleting a moved Control from one DockableContainer to another in TestScene.tscn no longer results in an error.
- [x] Loading layouts now always works. For some reason, using `clone()` on LayoutNodes was not working properly on layout loading. Removing clone() completely from these resources, and instead using `duplicate(true)` on layout's `clone()` method fixed the issue. Using `duplicate(true)` resulted in an error in Godot 3.x, but it seems to no longer be the case in Godot 4.
- [x] DockableContainer is now using the `child_entered_tree` and `child_exiting_tree` signals to handle child creation and deletion, instead of overriding `add_child()` and `remove_child()`, as overriding native non-virtual methods is not supported, and results in an error, if warning/error reporting is enabled for the addons folder (from the project settings).
- [x] Fix bug where sometimes the child controls' position and size wouldn't be updated. This is usually happened when I turned the visibility of a tab off, and the other tab appeared empty, until something else changed (resizing the container, changing tab, etc). Turns out NOTIFICATION_TRANSFORM_CHANGED is called even less for some reason in `dockable_panel_reference_control.gd`, so the reference wouldn't be repositioned. I fixed this by calling `_reposition_reference()` in `reference_to`'s setter.
- [x] Fixed code formatting/linting.

Overall code changes:
- [x] Most scripts now use `class_name` for their types, so other scripts can access them in global scope, instead of using script preloading. I think this is better practice for static typing, readability, and it gives users the option to reference them in areas outside of the addon, if they desire. To ensure that the addon class names do not conflict with anything else in people's projects, I have prefixed all of them with `Dockable`. For example, Layout is `DockableLayout`, as using Layout for a class_name seemed a bit too common and could've potentially caused issues in projects.
- [x] I took advantage of Godot 4's better static typing support and added it wherever I could, including using statically typed arrays. I think this improves the readability of the codebase, as certain variables and methods are a bit more clear now about the data they manipulate. Hopefully statically typed dictionaries soon become a thing as well!
- [x] As mentioned above, the LayoutNode's `clone()` methods have been replaced with simply Layout being duplicated, as this seems to be working better. Not exactly sure why though, but it's less code, so we shouldn't complain. I couldn't find any issues with this with my testing, but feel free to test for yourself.
- [x] Replaced `"""comments""" `with `##comments`, so Godot can generate documentation pages for the custom classes. This is a new handy feature in Godot 4, where it automatically generates a documentation page for every script ~~that has a `class_name`~~ **EDIT:** Correction, `class_name` is not required for a documentation page to be rendered. Not everything is documented, but that's probably a thing to do for the future.

Known issues:
- Re-arranging tabs that are in the same panel does not work. This is because `tab_changed` no longer gets fired on tab re-arrange, and TabContainer does not have any other signal for this, so there is no way to know whether a tab has been re-arranged. To fix this issue, I opened a PR to Godot (https://github.com/godotengine/godot/pull/76374) to add a `active_tab_rearranged` signal to TabContainer, that already existed in TabBar. It got merged, so I will open a new PR here to fix this issue when Godot 4.1 stable is out, [which is expected to release mid-summer](https://godotengine.org/article/release-management-4-1/).

### CODE REVIEW

**Comment by Gamemap** [comment]
Thank you very much for finishing the conversion.

**Comment by gilzoide** [comment]
Wow, that's awesome, thanks for this contribution! And sorry about the delay.
I'll try it here and review the changes today, thanks again!

**Comment by gilzoide** [comment]
Overall, everything seems fine, good work!

The only bug I found was with the "Visible Nodes" button in the layout property editor. If you press it twice, it seems to be duplicating child controls in the editor's DockableContainer. It does some layout reseting in the scene's container if you modify anything else in the layout after that. I couldn't pinpoint the cause of this bug yet, it totally makes no sense to me.

Thinking about having to clone the layout in the property editor, which seems super weird, and the problems we had with cloning the layout since the beginning of this project, maybe now is a good time to make that refactor of the Layout class using nested Dictionaries (or maybe `RefCounted` objects, if they get serialized correctly) instead of nested Resources. This way we would always have a single Resource with everything contained in it to deal with, which is surely a lot less error-prone. The plugin was not yet released for Godot 4.X so there should be less problem breaking compatibility with the saved Layout data structure. Version 2.0, (maybe) here we go!
What do you think? I know this is more work, but it would totally be done after this PR gets merged, so don't worry about it at all, I got this. Of course, I am open for suggestions about this, if you have any ^^

> Most scripts now use `class_name` for their types, so other scripts can access them in global scope, instead of using script preloading. I think this is better practice for static typing, readability, and it gives users the option to reference them in areas outside of the addon, if they desire.

To be honest, I don't think people would ever need/want to reference classes besides `DockableContainer` and the layout Resource types. I'd say that having, for example, `DockablePanel` and other internal classes registered to Godot, which mean they appear at the "Create New Node" dialog as well as being accessible to scripts globally, only adds clutter without any benefits.
Maybe the only internal class that makes sense to be used outside of the context of Dockable Containers is the `DockableReferenceControl`, since it is quite isolated and could theoretically be used elsewhere.

**Comment by OverloadedOrama** [comment]
> The only bug I found was with the "Visible Nodes" button in the layout property editor. If you press it twice, it seems to be duplicating child controls in the editor's DockableContainer. It does some layout reseting in the scene's container if you modify anything else in the layout after that. I couldn't pinpoint the cause of this bug yet, it totally makes no sense to me.

Good catch, I fixed this again by doing `clone()` after `_get_layout()`. To be honest I'm not sure why this is needed and I feel it may be a hacky solution, but it's the only one I could find so far, and it seems to be working.

> Thinking about having to clone the layout in the property editor, which seems super weird, and the problems we had with cloning the layout since the beginning of this project, maybe now is a good time to make that refactor of the Layout class using nested Dictionaries (or maybe `RefCounted` objects, if they get serialized correctly) instead of nested Resources. This way we would always have a single Resource with everything contained in it to deal with, which is surely a lot less error-prone. The plugin was not yet released for Godot 4.X so there should be less problem breaking compatibility with the saved Layout data structure. Version 2.0, (maybe) here we go! What do you think? I know this is more work, but it would totally be done after this PR gets merged, so don't worry about it at all, I got this. Of course, I am open for suggestions about this, if you have any ^^

Sounds good to me!

> To be honest, I don't think people would ever need/want to reference classes besides `DockableContainer` and the layout Resource types. I'd say that having, for example, `DockablePanel` and other internal classes registered to Godot, which mean they appear at the "Create New Node" dialog as well as being accessible to scripts globally, only adds clutter without any benefits. Maybe the only internal class that makes sense to be used outside of the context of Dockable Containers is the `DockableReferenceControl`, since it is quite isolated and could theoretically be used elsewhere.

You are right about the added clutter, I completely forgot about that. For now, I removed all of the class_names from the scripts that derive from Control nodes, with the exception of `DockableReferenceControl`. Let me know if you want me to remove the others as well (DockableLayoutNode, DockableLayoutPanel, etc). Since they don't extend a node, they don't clutter the "Create New Node" dialog. Although I think `DockableLayout` should definitely be globally accessible, in order to allow users to easily handle saving/loading of layouts in their projects.

I was under the impression that scripts that do not have a class_name do not have a documentation page rendered, but luckily that does not seem to be the case, so we're not losing much by removing class_name it seems like.

**Comment by gilzoide** [comment]
All right, thanks for the fixes! I think that cloning the layout won't be necessary after refactoring, but it's best that we maintain the code usable before this happens.

I'll create a `godot-3` branch from current `main` and this Godot 4.X code will be the new `main`. Then we continue improving it. I'll try to work on the layout refactor either this weekend or the next one, I'll let you know.

Thanks again, @Gamemap and @OverloadedOrama 🎉
Without you both this project would probably be in the limbo with only Godot 3.X support.

**Pull request merged**
